import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import YapProvider  from "@/context/yapcontext"; // Assuming you have YapContextProvider exported
import EventProvider from "@/context/eventcontext";
import MarketplaceProvider from "@/context/marketplacecontext";
import UserProvider from "@/context/usercontext";
import AuthProvider from "@/context/authcontext";
import { Toaster } from "react-hot-toast";
import ChatProvider from "@/context/chatcontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Camposocial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <Toaster
  position="top-center"
  reverseOrder={false}
  gutter={8}
  containerClassName=""
  containerStyle={{}}
  toastOptions={{
    // Define default options
    className: '',
    duration: 5000,
    style: {
      background: '#363636',
      color: '#fff',
    },

    // Default options for specific types
    success: {
      duration: 3000,
      theme: {
        primary: 'green',
        secondary: 'black',
      },
    },
  }}
/>        <UserProvider>
        <MarketplaceProvider>
        <EventProvider>
        <YapProvider>
          <ChatProvider>
          {children}
          </ChatProvider>
          </YapProvider>
        </EventProvider>
        </MarketplaceProvider></UserProvider></AuthProvider>
      </body>  
    </html>
  );
}
